
Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: leo
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update